name: run-tests
on:
  pull_request:
    paths:
      - ".github/workflows/run_tests.yml"
      - "truffle.config.js"
      - "contracts/**"
      - "test/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.9.1
      - name: create secret
        run: touch .secret && echo -e "load tank more range private galaxy connect aunt popular picnic grain waste" >> .secret
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Running tests
        run: yarn test
