name: Test Contract

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  test-contract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Lint Contract
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Test Contract
        uses: borales/actions-yarn@v4
        with:
          cmd: test
